./raytracer input/scenes/four_cubes/four_cubes_000.txt input/cameras/four_cubes/four_cubes_000.txt 
./raytracer input/scenes/four_cubes/four_cubes_001.txt input/cameras/four_cubes/four_cubes_001.txt 
./raytracer input/scenes/four_cubes/four_cubes_002.txt input/cameras/four_cubes/four_cubes_002.txt 
./raytracer input/scenes/four_cubes/four_cubes_003.txt input/cameras/four_cubes/four_cubes_003.txt 
./raytracer input/scenes/four_cubes/four_cubes_004.txt input/cameras/four_cubes/four_cubes_004.txt 
./raytracer input/scenes/four_cubes/four_cubes_005.txt input/cameras/four_cubes/four_cubes_005.txt 
./raytracer input/scenes/four_cubes/four_cubes_006.txt input/cameras/four_cubes/four_cubes_006.txt 
./raytracer input/scenes/four_cubes/four_cubes_007.txt input/cameras/four_cubes/four_cubes_007.txt 
./raytracer input/scenes/four_cubes/four_cubes_008.txt input/cameras/four_cubes/four_cubes_008.txt 
./raytracer input/scenes/four_cubes/four_cubes_009.txt input/cameras/four_cubes/four_cubes_009.txt 
./raytracer input/scenes/four_cubes/four_cubes_010.txt input/cameras/four_cubes/four_cubes_010.txt 
./raytracer input/scenes/four_cubes/four_cubes_011.txt input/cameras/four_cubes/four_cubes_011.txt 
./raytracer input/scenes/four_cubes/four_cubes_012.txt input/cameras/four_cubes/four_cubes_012.txt 
./raytracer input/scenes/four_cubes/four_cubes_013.txt input/cameras/four_cubes/four_cubes_013.txt 
./raytracer input/scenes/four_cubes/four_cubes_014.txt input/cameras/four_cubes/four_cubes_014.txt 
./raytracer input/scenes/four_cubes/four_cubes_015.txt input/cameras/four_cubes/four_cubes_015.txt 
./raytracer input/scenes/four_cubes/four_cubes_016.txt input/cameras/four_cubes/four_cubes_016.txt 
./raytracer input/scenes/four_cubes/four_cubes_017.txt input/cameras/four_cubes/four_cubes_017.txt 
./raytracer input/scenes/four_cubes/four_cubes_018.txt input/cameras/four_cubes/four_cubes_018.txt  
./raytracer input/scenes/four_cubes/four_cubes_019.txt input/cameras/four_cubes/four_cubes_019.txt 
./raytracer input/scenes/four_cubes/four_cubes_020.txt input/cameras/four_cubes/four_cubes_020.txt 
./raytracer input/scenes/four_cubes/four_cubes_021.txt input/cameras/four_cubes/four_cubes_021.txt 
./raytracer input/scenes/four_cubes/four_cubes_022.txt input/cameras/four_cubes/four_cubes_022.txt 
./raytracer input/scenes/four_cubes/four_cubes_023.txt input/cameras/four_cubes/four_cubes_023.txt 
./raytracer input/scenes/four_cubes/four_cubes_024.txt input/cameras/four_cubes/four_cubes_024.txt 
./raytracer input/scenes/four_cubes/four_cubes_025.txt input/cameras/four_cubes/four_cubes_025.txt 
./raytracer input/scenes/four_cubes/four_cubes_026.txt input/cameras/four_cubes/four_cubes_026.txt 
./raytracer input/scenes/four_cubes/four_cubes_027.txt input/cameras/four_cubes/four_cubes_027.txt 
./raytracer input/scenes/four_cubes/four_cubes_028.txt input/cameras/four_cubes/four_cubes_028.txt 
./raytracer input/scenes/four_cubes/four_cubes_029.txt input/cameras/four_cubes/four_cubes_029.txt 
./raytracer input/scenes/four_cubes/four_cubes_030.txt input/cameras/four_cubes/four_cubes_030.txt 
./raytracer input/scenes/four_cubes/four_cubes_031.txt input/cameras/four_cubes/four_cubes_031.txt 
./raytracer input/scenes/four_cubes/four_cubes_032.txt input/cameras/four_cubes/four_cubes_032.txt 
./raytracer input/scenes/four_cubes/four_cubes_033.txt input/cameras/four_cubes/four_cubes_033.txt 
./raytracer input/scenes/four_cubes/four_cubes_034.txt input/cameras/four_cubes/four_cubes_034.txt 
./raytracer input/scenes/four_cubes/four_cubes_035.txt input/cameras/four_cubes/four_cubes_035.txt 
./raytracer input/scenes/four_cubes/four_cubes_036.txt input/cameras/four_cubes/four_cubes_036.txt 
./raytracer input/scenes/four_cubes/four_cubes_037.txt input/cameras/four_cubes/four_cubes_037.txt 
./raytracer input/scenes/four_cubes/four_cubes_038.txt input/cameras/four_cubes/four_cubes_038.txt 
./raytracer input/scenes/four_cubes/four_cubes_039.txt input/cameras/four_cubes/four_cubes_039.txt 
./raytracer input/scenes/four_cubes/four_cubes_040.txt input/cameras/four_cubes/four_cubes_040.txt 
./raytracer input/scenes/four_cubes/four_cubes_041.txt input/cameras/four_cubes/four_cubes_041.txt 
./raytracer input/scenes/four_cubes/four_cubes_042.txt input/cameras/four_cubes/four_cubes_042.txt 
./raytracer input/scenes/four_cubes/four_cubes_043.txt input/cameras/four_cubes/four_cubes_043.txt 
./raytracer input/scenes/four_cubes/four_cubes_044.txt input/cameras/four_cubes/four_cubes_044.txt 
./raytracer input/scenes/four_cubes/four_cubes_045.txt input/cameras/four_cubes/four_cubes_045.txt 
./raytracer input/scenes/four_cubes/four_cubes_046.txt input/cameras/four_cubes/four_cubes_046.txt 
./raytracer input/scenes/four_cubes/four_cubes_047.txt input/cameras/four_cubes/four_cubes_047.txt 
./raytracer input/scenes/four_cubes/four_cubes_048.txt input/cameras/four_cubes/four_cubes_048.txt 
./raytracer input/scenes/four_cubes/four_cubes_049.txt input/cameras/four_cubes/four_cubes_049.txt 
./raytracer input/scenes/four_cubes/four_cubes_050.txt input/cameras/four_cubes/four_cubes_050.txt 
./raytracer input/scenes/four_cubes/four_cubes_051.txt input/cameras/four_cubes/four_cubes_051.txt 
./raytracer input/scenes/four_cubes/four_cubes_052.txt input/cameras/four_cubes/four_cubes_052.txt 
./raytracer input/scenes/four_cubes/four_cubes_053.txt input/cameras/four_cubes/four_cubes_053.txt 
./raytracer input/scenes/four_cubes/four_cubes_054.txt input/cameras/four_cubes/four_cubes_054.txt 
./raytracer input/scenes/four_cubes/four_cubes_055.txt input/cameras/four_cubes/four_cubes_055.txt 
./raytracer input/scenes/four_cubes/four_cubes_056.txt input/cameras/four_cubes/four_cubes_056.txt 
./raytracer input/scenes/four_cubes/four_cubes_057.txt input/cameras/four_cubes/four_cubes_057.txt 
./raytracer input/scenes/four_cubes/four_cubes_058.txt input/cameras/four_cubes/four_cubes_058.txt 
./raytracer input/scenes/four_cubes/four_cubes_059.txt input/cameras/four_cubes/four_cubes_059.txt 
./raytracer input/scenes/four_cubes/four_cubes_060.txt input/cameras/four_cubes/four_cubes_060.txt 
./raytracer input/scenes/four_cubes/four_cubes_061.txt input/cameras/four_cubes/four_cubes_061.txt 
./raytracer input/scenes/four_cubes/four_cubes_062.txt input/cameras/four_cubes/four_cubes_062.txt 
./raytracer input/scenes/four_cubes/four_cubes_063.txt input/cameras/four_cubes/four_cubes_063.txt 
./raytracer input/scenes/four_cubes/four_cubes_064.txt input/cameras/four_cubes/four_cubes_064.txt 
./raytracer input/scenes/four_cubes/four_cubes_065.txt input/cameras/four_cubes/four_cubes_065.txt 
./raytracer input/scenes/four_cubes/four_cubes_066.txt input/cameras/four_cubes/four_cubes_066.txt 
./raytracer input/scenes/four_cubes/four_cubes_067.txt input/cameras/four_cubes/four_cubes_067.txt 
./raytracer input/scenes/four_cubes/four_cubes_068.txt input/cameras/four_cubes/four_cubes_068.txt 
./raytracer input/scenes/four_cubes/four_cubes_069.txt input/cameras/four_cubes/four_cubes_069.txt 
./raytracer input/scenes/four_cubes/four_cubes_070.txt input/cameras/four_cubes/four_cubes_070.txt 
./raytracer input/scenes/four_cubes/four_cubes_071.txt input/cameras/four_cubes/four_cubes_071.txt 
./raytracer input/scenes/four_cubes/four_cubes_072.txt input/cameras/four_cubes/four_cubes_072.txt 
./raytracer input/scenes/four_cubes/four_cubes_073.txt input/cameras/four_cubes/four_cubes_073.txt 
./raytracer input/scenes/four_cubes/four_cubes_074.txt input/cameras/four_cubes/four_cubes_074.txt 
./raytracer input/scenes/four_cubes/four_cubes_075.txt input/cameras/four_cubes/four_cubes_075.txt 
./raytracer input/scenes/four_cubes/four_cubes_076.txt input/cameras/four_cubes/four_cubes_076.txt 
./raytracer input/scenes/four_cubes/four_cubes_077.txt input/cameras/four_cubes/four_cubes_077.txt 
./raytracer input/scenes/four_cubes/four_cubes_078.txt input/cameras/four_cubes/four_cubes_078.txt 
./raytracer input/scenes/four_cubes/four_cubes_079.txt input/cameras/four_cubes/four_cubes_079.txt 
./raytracer input/scenes/four_cubes/four_cubes_080.txt input/cameras/four_cubes/four_cubes_080.txt 
./raytracer input/scenes/four_cubes/four_cubes_081.txt input/cameras/four_cubes/four_cubes_081.txt 
./raytracer input/scenes/four_cubes/four_cubes_082.txt input/cameras/four_cubes/four_cubes_082.txt 
./raytracer input/scenes/four_cubes/four_cubes_083.txt input/cameras/four_cubes/four_cubes_083.txt 
./raytracer input/scenes/four_cubes/four_cubes_084.txt input/cameras/four_cubes/four_cubes_084.txt 
./raytracer input/scenes/four_cubes/four_cubes_085.txt input/cameras/four_cubes/four_cubes_085.txt 
./raytracer input/scenes/four_cubes/four_cubes_086.txt input/cameras/four_cubes/four_cubes_086.txt 
./raytracer input/scenes/four_cubes/four_cubes_087.txt input/cameras/four_cubes/four_cubes_087.txt 
./raytracer input/scenes/four_cubes/four_cubes_088.txt input/cameras/four_cubes/four_cubes_088.txt 
./raytracer input/scenes/four_cubes/four_cubes_089.txt input/cameras/four_cubes/four_cubes_089.txt 
./raytracer input/scenes/four_cubes/four_cubes_090.txt input/cameras/four_cubes/four_cubes_090.txt 
./raytracer input/scenes/four_cubes/four_cubes_091.txt input/cameras/four_cubes/four_cubes_091.txt 
./raytracer input/scenes/four_cubes/four_cubes_092.txt input/cameras/four_cubes/four_cubes_092.txt 
./raytracer input/scenes/four_cubes/four_cubes_093.txt input/cameras/four_cubes/four_cubes_093.txt 
./raytracer input/scenes/four_cubes/four_cubes_094.txt input/cameras/four_cubes/four_cubes_094.txt 
./raytracer input/scenes/four_cubes/four_cubes_095.txt input/cameras/four_cubes/four_cubes_095.txt 
./raytracer input/scenes/four_cubes/four_cubes_096.txt input/cameras/four_cubes/four_cubes_096.txt 
./raytracer input/scenes/four_cubes/four_cubes_097.txt input/cameras/four_cubes/four_cubes_097.txt 
./raytracer input/scenes/four_cubes/four_cubes_098.txt input/cameras/four_cubes/four_cubes_098.txt 
./raytracer input/scenes/four_cubes/four_cubes_099.txt input/cameras/four_cubes/four_cubes_099.txt 
./raytracer input/scenes/four_cubes/four_cubes_100.txt input/cameras/four_cubes/four_cubes_100.txt 
./raytracer input/scenes/four_cubes/four_cubes_101.txt input/cameras/four_cubes/four_cubes_101.txt 
./raytracer input/scenes/four_cubes/four_cubes_102.txt input/cameras/four_cubes/four_cubes_102.txt 
./raytracer input/scenes/four_cubes/four_cubes_103.txt input/cameras/four_cubes/four_cubes_103.txt 
./raytracer input/scenes/four_cubes/four_cubes_104.txt input/cameras/four_cubes/four_cubes_104.txt 
./raytracer input/scenes/four_cubes/four_cubes_105.txt input/cameras/four_cubes/four_cubes_105.txt 
./raytracer input/scenes/four_cubes/four_cubes_106.txt input/cameras/four_cubes/four_cubes_106.txt 
./raytracer input/scenes/four_cubes/four_cubes_107.txt input/cameras/four_cubes/four_cubes_107.txt 
./raytracer input/scenes/four_cubes/four_cubes_108.txt input/cameras/four_cubes/four_cubes_108.txt 
./raytracer input/scenes/four_cubes/four_cubes_109.txt input/cameras/four_cubes/four_cubes_109.txt 
./raytracer input/scenes/four_cubes/four_cubes_110.txt input/cameras/four_cubes/four_cubes_110.txt 
./raytracer input/scenes/four_cubes/four_cubes_111.txt input/cameras/four_cubes/four_cubes_111.txt 
./raytracer input/scenes/four_cubes/four_cubes_112.txt input/cameras/four_cubes/four_cubes_112.txt 
./raytracer input/scenes/four_cubes/four_cubes_113.txt input/cameras/four_cubes/four_cubes_113.txt 
./raytracer input/scenes/four_cubes/four_cubes_114.txt input/cameras/four_cubes/four_cubes_114.txt 
./raytracer input/scenes/four_cubes/four_cubes_115.txt input/cameras/four_cubes/four_cubes_115.txt 
./raytracer input/scenes/four_cubes/four_cubes_116.txt input/cameras/four_cubes/four_cubes_116.txt 
./raytracer input/scenes/four_cubes/four_cubes_117.txt input/cameras/four_cubes/four_cubes_117.txt 
./raytracer input/scenes/four_cubes/four_cubes_118.txt input/cameras/four_cubes/four_cubes_118.txt  
./raytracer input/scenes/four_cubes/four_cubes_119.txt input/cameras/four_cubes/four_cubes_119.txt 
./raytracer input/scenes/four_cubes/four_cubes_120.txt input/cameras/four_cubes/four_cubes_120.txt 
./raytracer input/scenes/four_cubes/four_cubes_121.txt input/cameras/four_cubes/four_cubes_121.txt 
./raytracer input/scenes/four_cubes/four_cubes_122.txt input/cameras/four_cubes/four_cubes_122.txt 
./raytracer input/scenes/four_cubes/four_cubes_123.txt input/cameras/four_cubes/four_cubes_123.txt 
./raytracer input/scenes/four_cubes/four_cubes_124.txt input/cameras/four_cubes/four_cubes_124.txt 
./raytracer input/scenes/four_cubes/four_cubes_125.txt input/cameras/four_cubes/four_cubes_125.txt 
./raytracer input/scenes/four_cubes/four_cubes_126.txt input/cameras/four_cubes/four_cubes_126.txt 
./raytracer input/scenes/four_cubes/four_cubes_127.txt input/cameras/four_cubes/four_cubes_127.txt 
./raytracer input/scenes/four_cubes/four_cubes_128.txt input/cameras/four_cubes/four_cubes_128.txt 
./raytracer input/scenes/four_cubes/four_cubes_129.txt input/cameras/four_cubes/four_cubes_129.txt 
./raytracer input/scenes/four_cubes/four_cubes_130.txt input/cameras/four_cubes/four_cubes_130.txt 
./raytracer input/scenes/four_cubes/four_cubes_131.txt input/cameras/four_cubes/four_cubes_131.txt 
./raytracer input/scenes/four_cubes/four_cubes_132.txt input/cameras/four_cubes/four_cubes_132.txt 
./raytracer input/scenes/four_cubes/four_cubes_133.txt input/cameras/four_cubes/four_cubes_133.txt 
./raytracer input/scenes/four_cubes/four_cubes_134.txt input/cameras/four_cubes/four_cubes_134.txt 
./raytracer input/scenes/four_cubes/four_cubes_135.txt input/cameras/four_cubes/four_cubes_135.txt 
./raytracer input/scenes/four_cubes/four_cubes_136.txt input/cameras/four_cubes/four_cubes_136.txt 
./raytracer input/scenes/four_cubes/four_cubes_137.txt input/cameras/four_cubes/four_cubes_137.txt 
./raytracer input/scenes/four_cubes/four_cubes_138.txt input/cameras/four_cubes/four_cubes_138.txt 
./raytracer input/scenes/four_cubes/four_cubes_139.txt input/cameras/four_cubes/four_cubes_139.txt 
./raytracer input/scenes/four_cubes/four_cubes_140.txt input/cameras/four_cubes/four_cubes_140.txt 
./raytracer input/scenes/four_cubes/four_cubes_141.txt input/cameras/four_cubes/four_cubes_141.txt 
./raytracer input/scenes/four_cubes/four_cubes_142.txt input/cameras/four_cubes/four_cubes_142.txt 
./raytracer input/scenes/four_cubes/four_cubes_143.txt input/cameras/four_cubes/four_cubes_143.txt 
./raytracer input/scenes/four_cubes/four_cubes_144.txt input/cameras/four_cubes/four_cubes_144.txt 
./raytracer input/scenes/four_cubes/four_cubes_145.txt input/cameras/four_cubes/four_cubes_145.txt 
./raytracer input/scenes/four_cubes/four_cubes_146.txt input/cameras/four_cubes/four_cubes_146.txt 
./raytracer input/scenes/four_cubes/four_cubes_147.txt input/cameras/four_cubes/four_cubes_147.txt 
./raytracer input/scenes/four_cubes/four_cubes_148.txt input/cameras/four_cubes/four_cubes_148.txt 
./raytracer input/scenes/four_cubes/four_cubes_149.txt input/cameras/four_cubes/four_cubes_149.txt 
./raytracer input/scenes/four_cubes/four_cubes_150.txt input/cameras/four_cubes/four_cubes_150.txt 
./raytracer input/scenes/four_cubes/four_cubes_151.txt input/cameras/four_cubes/four_cubes_151.txt 
./raytracer input/scenes/four_cubes/four_cubes_152.txt input/cameras/four_cubes/four_cubes_152.txt 
./raytracer input/scenes/four_cubes/four_cubes_153.txt input/cameras/four_cubes/four_cubes_153.txt 
./raytracer input/scenes/four_cubes/four_cubes_154.txt input/cameras/four_cubes/four_cubes_154.txt 
./raytracer input/scenes/four_cubes/four_cubes_155.txt input/cameras/four_cubes/four_cubes_155.txt 
./raytracer input/scenes/four_cubes/four_cubes_156.txt input/cameras/four_cubes/four_cubes_156.txt 
./raytracer input/scenes/four_cubes/four_cubes_157.txt input/cameras/four_cubes/four_cubes_157.txt 
./raytracer input/scenes/four_cubes/four_cubes_158.txt input/cameras/four_cubes/four_cubes_158.txt 
./raytracer input/scenes/four_cubes/four_cubes_159.txt input/cameras/four_cubes/four_cubes_159.txt 
./raytracer input/scenes/four_cubes/four_cubes_160.txt input/cameras/four_cubes/four_cubes_160.txt 
./raytracer input/scenes/four_cubes/four_cubes_161.txt input/cameras/four_cubes/four_cubes_161.txt 
./raytracer input/scenes/four_cubes/four_cubes_162.txt input/cameras/four_cubes/four_cubes_162.txt 
./raytracer input/scenes/four_cubes/four_cubes_163.txt input/cameras/four_cubes/four_cubes_163.txt 
./raytracer input/scenes/four_cubes/four_cubes_164.txt input/cameras/four_cubes/four_cubes_164.txt 
./raytracer input/scenes/four_cubes/four_cubes_165.txt input/cameras/four_cubes/four_cubes_165.txt 
./raytracer input/scenes/four_cubes/four_cubes_166.txt input/cameras/four_cubes/four_cubes_166.txt 
./raytracer input/scenes/four_cubes/four_cubes_167.txt input/cameras/four_cubes/four_cubes_167.txt 
./raytracer input/scenes/four_cubes/four_cubes_168.txt input/cameras/four_cubes/four_cubes_168.txt 
./raytracer input/scenes/four_cubes/four_cubes_169.txt input/cameras/four_cubes/four_cubes_169.txt 
./raytracer input/scenes/four_cubes/four_cubes_170.txt input/cameras/four_cubes/four_cubes_170.txt 
./raytracer input/scenes/four_cubes/four_cubes_171.txt input/cameras/four_cubes/four_cubes_171.txt 
./raytracer input/scenes/four_cubes/four_cubes_172.txt input/cameras/four_cubes/four_cubes_172.txt 
./raytracer input/scenes/four_cubes/four_cubes_173.txt input/cameras/four_cubes/four_cubes_173.txt 
./raytracer input/scenes/four_cubes/four_cubes_174.txt input/cameras/four_cubes/four_cubes_174.txt 
./raytracer input/scenes/four_cubes/four_cubes_175.txt input/cameras/four_cubes/four_cubes_175.txt 
./raytracer input/scenes/four_cubes/four_cubes_176.txt input/cameras/four_cubes/four_cubes_176.txt 
./raytracer input/scenes/four_cubes/four_cubes_177.txt input/cameras/four_cubes/four_cubes_177.txt 
./raytracer input/scenes/four_cubes/four_cubes_178.txt input/cameras/four_cubes/four_cubes_178.txt 
./raytracer input/scenes/four_cubes/four_cubes_179.txt input/cameras/four_cubes/four_cubes_179.txt 
./raytracer input/scenes/four_cubes/four_cubes_180.txt input/cameras/four_cubes/four_cubes_180.txt 
./raytracer input/scenes/four_cubes/four_cubes_181.txt input/cameras/four_cubes/four_cubes_181.txt 
./raytracer input/scenes/four_cubes/four_cubes_182.txt input/cameras/four_cubes/four_cubes_182.txt 
./raytracer input/scenes/four_cubes/four_cubes_183.txt input/cameras/four_cubes/four_cubes_183.txt 
./raytracer input/scenes/four_cubes/four_cubes_184.txt input/cameras/four_cubes/four_cubes_184.txt 
./raytracer input/scenes/four_cubes/four_cubes_185.txt input/cameras/four_cubes/four_cubes_185.txt 
./raytracer input/scenes/four_cubes/four_cubes_186.txt input/cameras/four_cubes/four_cubes_186.txt 
./raytracer input/scenes/four_cubes/four_cubes_187.txt input/cameras/four_cubes/four_cubes_187.txt 
./raytracer input/scenes/four_cubes/four_cubes_188.txt input/cameras/four_cubes/four_cubes_188.txt 
./raytracer input/scenes/four_cubes/four_cubes_189.txt input/cameras/four_cubes/four_cubes_189.txt 
./raytracer input/scenes/four_cubes/four_cubes_190.txt input/cameras/four_cubes/four_cubes_190.txt 
./raytracer input/scenes/four_cubes/four_cubes_191.txt input/cameras/four_cubes/four_cubes_191.txt 
./raytracer input/scenes/four_cubes/four_cubes_192.txt input/cameras/four_cubes/four_cubes_192.txt 
./raytracer input/scenes/four_cubes/four_cubes_193.txt input/cameras/four_cubes/four_cubes_193.txt 
./raytracer input/scenes/four_cubes/four_cubes_194.txt input/cameras/four_cubes/four_cubes_194.txt 
./raytracer input/scenes/four_cubes/four_cubes_195.txt input/cameras/four_cubes/four_cubes_195.txt 
./raytracer input/scenes/four_cubes/four_cubes_196.txt input/cameras/four_cubes/four_cubes_196.txt 
./raytracer input/scenes/four_cubes/four_cubes_197.txt input/cameras/four_cubes/four_cubes_197.txt 
./raytracer input/scenes/four_cubes/four_cubes_198.txt input/cameras/four_cubes/four_cubes_198.txt 
./raytracer input/scenes/four_cubes/four_cubes_199.txt input/cameras/four_cubes/four_cubes_199.txt 
./raytracer input/scenes/four_cubes/four_cubes_200.txt input/cameras/four_cubes/four_cubes_200.txt 
./raytracer input/scenes/four_cubes/four_cubes_201.txt input/cameras/four_cubes/four_cubes_201.txt 
./raytracer input/scenes/four_cubes/four_cubes_202.txt input/cameras/four_cubes/four_cubes_202.txt 
./raytracer input/scenes/four_cubes/four_cubes_203.txt input/cameras/four_cubes/four_cubes_203.txt 
./raytracer input/scenes/four_cubes/four_cubes_204.txt input/cameras/four_cubes/four_cubes_204.txt 
./raytracer input/scenes/four_cubes/four_cubes_205.txt input/cameras/four_cubes/four_cubes_205.txt 
./raytracer input/scenes/four_cubes/four_cubes_206.txt input/cameras/four_cubes/four_cubes_206.txt 
./raytracer input/scenes/four_cubes/four_cubes_207.txt input/cameras/four_cubes/four_cubes_207.txt 
./raytracer input/scenes/four_cubes/four_cubes_208.txt input/cameras/four_cubes/four_cubes_208.txt 
./raytracer input/scenes/four_cubes/four_cubes_209.txt input/cameras/four_cubes/four_cubes_209.txt 
./raytracer input/scenes/four_cubes/four_cubes_210.txt input/cameras/four_cubes/four_cubes_210.txt 
./raytracer input/scenes/four_cubes/four_cubes_211.txt input/cameras/four_cubes/four_cubes_211.txt 
./raytracer input/scenes/four_cubes/four_cubes_212.txt input/cameras/four_cubes/four_cubes_212.txt 
./raytracer input/scenes/four_cubes/four_cubes_213.txt input/cameras/four_cubes/four_cubes_213.txt 
./raytracer input/scenes/four_cubes/four_cubes_214.txt input/cameras/four_cubes/four_cubes_214.txt 
./raytracer input/scenes/four_cubes/four_cubes_215.txt input/cameras/four_cubes/four_cubes_215.txt 
./raytracer input/scenes/four_cubes/four_cubes_216.txt input/cameras/four_cubes/four_cubes_216.txt 
./raytracer input/scenes/four_cubes/four_cubes_217.txt input/cameras/four_cubes/four_cubes_217.txt 
./raytracer input/scenes/four_cubes/four_cubes_218.txt input/cameras/four_cubes/four_cubes_218.txt  
./raytracer input/scenes/four_cubes/four_cubes_219.txt input/cameras/four_cubes/four_cubes_219.txt 
./raytracer input/scenes/four_cubes/four_cubes_220.txt input/cameras/four_cubes/four_cubes_220.txt 
./raytracer input/scenes/four_cubes/four_cubes_221.txt input/cameras/four_cubes/four_cubes_221.txt 
./raytracer input/scenes/four_cubes/four_cubes_222.txt input/cameras/four_cubes/four_cubes_222.txt 
./raytracer input/scenes/four_cubes/four_cubes_223.txt input/cameras/four_cubes/four_cubes_223.txt 
./raytracer input/scenes/four_cubes/four_cubes_224.txt input/cameras/four_cubes/four_cubes_224.txt 
./raytracer input/scenes/four_cubes/four_cubes_225.txt input/cameras/four_cubes/four_cubes_225.txt 
./raytracer input/scenes/four_cubes/four_cubes_226.txt input/cameras/four_cubes/four_cubes_226.txt 
./raytracer input/scenes/four_cubes/four_cubes_227.txt input/cameras/four_cubes/four_cubes_227.txt 
./raytracer input/scenes/four_cubes/four_cubes_228.txt input/cameras/four_cubes/four_cubes_228.txt 
./raytracer input/scenes/four_cubes/four_cubes_229.txt input/cameras/four_cubes/four_cubes_229.txt 
./raytracer input/scenes/four_cubes/four_cubes_230.txt input/cameras/four_cubes/four_cubes_230.txt 
./raytracer input/scenes/four_cubes/four_cubes_231.txt input/cameras/four_cubes/four_cubes_231.txt 
./raytracer input/scenes/four_cubes/four_cubes_232.txt input/cameras/four_cubes/four_cubes_232.txt 
./raytracer input/scenes/four_cubes/four_cubes_233.txt input/cameras/four_cubes/four_cubes_233.txt 
./raytracer input/scenes/four_cubes/four_cubes_234.txt input/cameras/four_cubes/four_cubes_234.txt 
./raytracer input/scenes/four_cubes/four_cubes_235.txt input/cameras/four_cubes/four_cubes_235.txt 
./raytracer input/scenes/four_cubes/four_cubes_236.txt input/cameras/four_cubes/four_cubes_236.txt 
./raytracer input/scenes/four_cubes/four_cubes_237.txt input/cameras/four_cubes/four_cubes_237.txt 
./raytracer input/scenes/four_cubes/four_cubes_238.txt input/cameras/four_cubes/four_cubes_238.txt 
./raytracer input/scenes/four_cubes/four_cubes_239.txt input/cameras/four_cubes/four_cubes_239.txt 
./raytracer input/scenes/four_cubes/four_cubes_240.txt input/cameras/four_cubes/four_cubes_240.txt 
./raytracer input/scenes/four_cubes/four_cubes_241.txt input/cameras/four_cubes/four_cubes_241.txt 
./raytracer input/scenes/four_cubes/four_cubes_242.txt input/cameras/four_cubes/four_cubes_242.txt 
./raytracer input/scenes/four_cubes/four_cubes_243.txt input/cameras/four_cubes/four_cubes_243.txt 
./raytracer input/scenes/four_cubes/four_cubes_244.txt input/cameras/four_cubes/four_cubes_244.txt 
./raytracer input/scenes/four_cubes/four_cubes_245.txt input/cameras/four_cubes/four_cubes_245.txt 
./raytracer input/scenes/four_cubes/four_cubes_246.txt input/cameras/four_cubes/four_cubes_246.txt 
./raytracer input/scenes/four_cubes/four_cubes_247.txt input/cameras/four_cubes/four_cubes_247.txt 
./raytracer input/scenes/four_cubes/four_cubes_248.txt input/cameras/four_cubes/four_cubes_248.txt 
./raytracer input/scenes/four_cubes/four_cubes_249.txt input/cameras/four_cubes/four_cubes_249.txt 
./raytracer input/scenes/four_cubes/four_cubes_250.txt input/cameras/four_cubes/four_cubes_250.txt 
./raytracer input/scenes/four_cubes/four_cubes_251.txt input/cameras/four_cubes/four_cubes_251.txt 
./raytracer input/scenes/four_cubes/four_cubes_252.txt input/cameras/four_cubes/four_cubes_252.txt 
./raytracer input/scenes/four_cubes/four_cubes_253.txt input/cameras/four_cubes/four_cubes_253.txt 
./raytracer input/scenes/four_cubes/four_cubes_254.txt input/cameras/four_cubes/four_cubes_254.txt 
./raytracer input/scenes/four_cubes/four_cubes_255.txt input/cameras/four_cubes/four_cubes_255.txt 
./raytracer input/scenes/four_cubes/four_cubes_256.txt input/cameras/four_cubes/four_cubes_256.txt 
./raytracer input/scenes/four_cubes/four_cubes_257.txt input/cameras/four_cubes/four_cubes_257.txt 
./raytracer input/scenes/four_cubes/four_cubes_258.txt input/cameras/four_cubes/four_cubes_258.txt 
./raytracer input/scenes/four_cubes/four_cubes_259.txt input/cameras/four_cubes/four_cubes_259.txt 
./raytracer input/scenes/four_cubes/four_cubes_260.txt input/cameras/four_cubes/four_cubes_260.txt 
./raytracer input/scenes/four_cubes/four_cubes_261.txt input/cameras/four_cubes/four_cubes_261.txt 
./raytracer input/scenes/four_cubes/four_cubes_262.txt input/cameras/four_cubes/four_cubes_262.txt 
./raytracer input/scenes/four_cubes/four_cubes_263.txt input/cameras/four_cubes/four_cubes_263.txt 
./raytracer input/scenes/four_cubes/four_cubes_264.txt input/cameras/four_cubes/four_cubes_264.txt 
./raytracer input/scenes/four_cubes/four_cubes_265.txt input/cameras/four_cubes/four_cubes_265.txt 
./raytracer input/scenes/four_cubes/four_cubes_266.txt input/cameras/four_cubes/four_cubes_266.txt 
./raytracer input/scenes/four_cubes/four_cubes_267.txt input/cameras/four_cubes/four_cubes_267.txt 
./raytracer input/scenes/four_cubes/four_cubes_268.txt input/cameras/four_cubes/four_cubes_268.txt 
./raytracer input/scenes/four_cubes/four_cubes_269.txt input/cameras/four_cubes/four_cubes_269.txt 
./raytracer input/scenes/four_cubes/four_cubes_270.txt input/cameras/four_cubes/four_cubes_270.txt 
./raytracer input/scenes/four_cubes/four_cubes_271.txt input/cameras/four_cubes/four_cubes_271.txt 
./raytracer input/scenes/four_cubes/four_cubes_272.txt input/cameras/four_cubes/four_cubes_272.txt 
./raytracer input/scenes/four_cubes/four_cubes_273.txt input/cameras/four_cubes/four_cubes_273.txt 
./raytracer input/scenes/four_cubes/four_cubes_274.txt input/cameras/four_cubes/four_cubes_274.txt 
./raytracer input/scenes/four_cubes/four_cubes_275.txt input/cameras/four_cubes/four_cubes_275.txt
./raytracer input/scenes/four_cubes/four_cubes_276.txt input/cameras/four_cubes/four_cubes_276.txt
./raytracer input/scenes/four_cubes/four_cubes_277.txt input/cameras/four_cubes/four_cubes_277.txt
./raytracer input/scenes/four_cubes/four_cubes_278.txt input/cameras/four_cubes/four_cubes_278.txt
./raytracer input/scenes/four_cubes/four_cubes_279.txt input/cameras/four_cubes/four_cubes_279.txt
./raytracer input/scenes/four_cubes/four_cubes_280.txt input/cameras/four_cubes/four_cubes_280.txt
./raytracer input/scenes/four_cubes/four_cubes_281.txt input/cameras/four_cubes/four_cubes_281.txt
./raytracer input/scenes/four_cubes/four_cubes_282.txt input/cameras/four_cubes/four_cubes_282.txt
./raytracer input/scenes/four_cubes/four_cubes_283.txt input/cameras/four_cubes/four_cubes_283.txt
./raytracer input/scenes/four_cubes/four_cubes_284.txt input/cameras/four_cubes/four_cubes_284.txt
./raytracer input/scenes/four_cubes/four_cubes_285.txt input/cameras/four_cubes/four_cubes_285.txt
./raytracer input/scenes/four_cubes/four_cubes_286.txt input/cameras/four_cubes/four_cubes_286.txt
./raytracer input/scenes/four_cubes/four_cubes_287.txt input/cameras/four_cubes/four_cubes_287.txt
./raytracer input/scenes/four_cubes/four_cubes_288.txt input/cameras/four_cubes/four_cubes_288.txt
./raytracer input/scenes/four_cubes/four_cubes_289.txt input/cameras/four_cubes/four_cubes_289.txt
./raytracer input/scenes/four_cubes/four_cubes_290.txt input/cameras/four_cubes/four_cubes_290.txt
./raytracer input/scenes/four_cubes/four_cubes_291.txt input/cameras/four_cubes/four_cubes_291.txt
./raytracer input/scenes/four_cubes/four_cubes_292.txt input/cameras/four_cubes/four_cubes_292.txt
./raytracer input/scenes/four_cubes/four_cubes_293.txt input/cameras/four_cubes/four_cubes_293.txt
./raytracer input/scenes/four_cubes/four_cubes_294.txt input/cameras/four_cubes/four_cubes_294.txt
./raytracer input/scenes/four_cubes/four_cubes_295.txt input/cameras/four_cubes/four_cubes_295.txt
./raytracer input/scenes/four_cubes/four_cubes_296.txt input/cameras/four_cubes/four_cubes_296.txt
./raytracer input/scenes/four_cubes/four_cubes_297.txt input/cameras/four_cubes/four_cubes_297.txt
./raytracer input/scenes/four_cubes/four_cubes_298.txt input/cameras/four_cubes/four_cubes_298.txt
./raytracer input/scenes/four_cubes/four_cubes_299.txt input/cameras/four_cubes/four_cubes_299.txt
./raytracer input/scenes/four_cubes/four_cubes_300.txt input/cameras/four_cubes/four_cubes_300.txt
./raytracer input/scenes/four_cubes/four_cubes_301.txt input/cameras/four_cubes/four_cubes_301.txt
./raytracer input/scenes/four_cubes/four_cubes_302.txt input/cameras/four_cubes/four_cubes_302.txt
./raytracer input/scenes/four_cubes/four_cubes_303.txt input/cameras/four_cubes/four_cubes_303.txt
./raytracer input/scenes/four_cubes/four_cubes_304.txt input/cameras/four_cubes/four_cubes_304.txt
./raytracer input/scenes/four_cubes/four_cubes_305.txt input/cameras/four_cubes/four_cubes_305.txt
./raytracer input/scenes/four_cubes/four_cubes_306.txt input/cameras/four_cubes/four_cubes_306.txt
./raytracer input/scenes/four_cubes/four_cubes_307.txt input/cameras/four_cubes/four_cubes_307.txt
./raytracer input/scenes/four_cubes/four_cubes_308.txt input/cameras/four_cubes/four_cubes_308.txt
./raytracer input/scenes/four_cubes/four_cubes_309.txt input/cameras/four_cubes/four_cubes_309.txt
./raytracer input/scenes/four_cubes/four_cubes_310.txt input/cameras/four_cubes/four_cubes_310.txt
./raytracer input/scenes/four_cubes/four_cubes_311.txt input/cameras/four_cubes/four_cubes_311.txt
./raytracer input/scenes/four_cubes/four_cubes_312.txt input/cameras/four_cubes/four_cubes_312.txt
./raytracer input/scenes/four_cubes/four_cubes_313.txt input/cameras/four_cubes/four_cubes_313.txt
./raytracer input/scenes/four_cubes/four_cubes_314.txt input/cameras/four_cubes/four_cubes_314.txt
./raytracer input/scenes/four_cubes/four_cubes_315.txt input/cameras/four_cubes/four_cubes_315.txt
./raytracer input/scenes/four_cubes/four_cubes_316.txt input/cameras/four_cubes/four_cubes_316.txt
./raytracer input/scenes/four_cubes/four_cubes_317.txt input/cameras/four_cubes/four_cubes_317.txt
./raytracer input/scenes/four_cubes/four_cubes_318.txt input/cameras/four_cubes/four_cubes_318.txt
./raytracer input/scenes/four_cubes/four_cubes_319.txt input/cameras/four_cubes/four_cubes_319.txt
./raytracer input/scenes/four_cubes/four_cubes_320.txt input/cameras/four_cubes/four_cubes_320.txt
./raytracer input/scenes/four_cubes/four_cubes_321.txt input/cameras/four_cubes/four_cubes_321.txt
./raytracer input/scenes/four_cubes/four_cubes_322.txt input/cameras/four_cubes/four_cubes_322.txt
./raytracer input/scenes/four_cubes/four_cubes_323.txt input/cameras/four_cubes/four_cubes_323.txt
./raytracer input/scenes/four_cubes/four_cubes_324.txt input/cameras/four_cubes/four_cubes_324.txt
./raytracer input/scenes/four_cubes/four_cubes_325.txt input/cameras/four_cubes/four_cubes_325.txt
./raytracer input/scenes/four_cubes/four_cubes_326.txt input/cameras/four_cubes/four_cubes_326.txt
./raytracer input/scenes/four_cubes/four_cubes_327.txt input/cameras/four_cubes/four_cubes_327.txt
./raytracer input/scenes/four_cubes/four_cubes_328.txt input/cameras/four_cubes/four_cubes_328.txt
./raytracer input/scenes/four_cubes/four_cubes_329.txt input/cameras/four_cubes/four_cubes_329.txt
./raytracer input/scenes/four_cubes/four_cubes_330.txt input/cameras/four_cubes/four_cubes_330.txt
./raytracer input/scenes/four_cubes/four_cubes_331.txt input/cameras/four_cubes/four_cubes_331.txt
./raytracer input/scenes/four_cubes/four_cubes_332.txt input/cameras/four_cubes/four_cubes_332.txt
./raytracer input/scenes/four_cubes/four_cubes_333.txt input/cameras/four_cubes/four_cubes_333.txt
./raytracer input/scenes/four_cubes/four_cubes_334.txt input/cameras/four_cubes/four_cubes_334.txt
./raytracer input/scenes/four_cubes/four_cubes_335.txt input/cameras/four_cubes/four_cubes_335.txt
./raytracer input/scenes/four_cubes/four_cubes_336.txt input/cameras/four_cubes/four_cubes_336.txt
./raytracer input/scenes/four_cubes/four_cubes_337.txt input/cameras/four_cubes/four_cubes_337.txt
./raytracer input/scenes/four_cubes/four_cubes_338.txt input/cameras/four_cubes/four_cubes_338.txt
./raytracer input/scenes/four_cubes/four_cubes_339.txt input/cameras/four_cubes/four_cubes_339.txt
./raytracer input/scenes/four_cubes/four_cubes_340.txt input/cameras/four_cubes/four_cubes_340.txt
./raytracer input/scenes/four_cubes/four_cubes_341.txt input/cameras/four_cubes/four_cubes_341.txt
./raytracer input/scenes/four_cubes/four_cubes_342.txt input/cameras/four_cubes/four_cubes_342.txt
./raytracer input/scenes/four_cubes/four_cubes_343.txt input/cameras/four_cubes/four_cubes_343.txt
./raytracer input/scenes/four_cubes/four_cubes_344.txt input/cameras/four_cubes/four_cubes_344.txt
./raytracer input/scenes/four_cubes/four_cubes_345.txt input/cameras/four_cubes/four_cubes_345.txt
./raytracer input/scenes/four_cubes/four_cubes_346.txt input/cameras/four_cubes/four_cubes_346.txt
./raytracer input/scenes/four_cubes/four_cubes_347.txt input/cameras/four_cubes/four_cubes_347.txt
./raytracer input/scenes/four_cubes/four_cubes_348.txt input/cameras/four_cubes/four_cubes_348.txt
./raytracer input/scenes/four_cubes/four_cubes_349.txt input/cameras/four_cubes/four_cubes_349.txt
./raytracer input/scenes/four_cubes/four_cubes_350.txt input/cameras/four_cubes/four_cubes_350.txt
./raytracer input/scenes/four_cubes/four_cubes_351.txt input/cameras/four_cubes/four_cubes_351.txt
./raytracer input/scenes/four_cubes/four_cubes_352.txt input/cameras/four_cubes/four_cubes_352.txt
./raytracer input/scenes/four_cubes/four_cubes_353.txt input/cameras/four_cubes/four_cubes_353.txt
./raytracer input/scenes/four_cubes/four_cubes_354.txt input/cameras/four_cubes/four_cubes_354.txt
./raytracer input/scenes/four_cubes/four_cubes_355.txt input/cameras/four_cubes/four_cubes_355.txt
./raytracer input/scenes/four_cubes/four_cubes_356.txt input/cameras/four_cubes/four_cubes_356.txt
./raytracer input/scenes/four_cubes/four_cubes_357.txt input/cameras/four_cubes/four_cubes_357.txt
./raytracer input/scenes/four_cubes/four_cubes_358.txt input/cameras/four_cubes/four_cubes_358.txt
./raytracer input/scenes/four_cubes/four_cubes_359.txt input/cameras/four_cubes/four_cubes_359.txt
./raytracer input/scenes/four_cubes/four_cubes_360.txt input/cameras/four_cubes/four_cubes_360.txt