./raytracer input/scenes/four_cubes/four_cubes_276.txt input/cameras/four_cubes/four_cubes_276.txt 
./raytracer input/scenes/four_cubes/four_cubes_277.txt input/cameras/four_cubes/four_cubes_277.txt 
./raytracer input/scenes/four_cubes/four_cubes_278.txt input/cameras/four_cubes/four_cubes_278.txt 
./raytracer input/scenes/four_cubes/four_cubes_279.txt input/cameras/four_cubes/four_cubes_279.txt 
./raytracer input/scenes/four_cubes/four_cubes_280.txt input/cameras/four_cubes/four_cubes_280.txt 
./raytracer input/scenes/four_cubes/four_cubes_281.txt input/cameras/four_cubes/four_cubes_281.txt 
./raytracer input/scenes/four_cubes/four_cubes_282.txt input/cameras/four_cubes/four_cubes_282.txt 
./raytracer input/scenes/four_cubes/four_cubes_283.txt input/cameras/four_cubes/four_cubes_283.txt 
./raytracer input/scenes/four_cubes/four_cubes_284.txt input/cameras/four_cubes/four_cubes_284.txt 
./raytracer input/scenes/four_cubes/four_cubes_285.txt input/cameras/four_cubes/four_cubes_285.txt 
./raytracer input/scenes/four_cubes/four_cubes_286.txt input/cameras/four_cubes/four_cubes_286.txt 
./raytracer input/scenes/four_cubes/four_cubes_287.txt input/cameras/four_cubes/four_cubes_287.txt 
./raytracer input/scenes/four_cubes/four_cubes_288.txt input/cameras/four_cubes/four_cubes_288.txt 
./raytracer input/scenes/four_cubes/four_cubes_289.txt input/cameras/four_cubes/four_cubes_289.txt 
./raytracer input/scenes/four_cubes/four_cubes_290.txt input/cameras/four_cubes/four_cubes_290.txt 
./raytracer input/scenes/four_cubes/four_cubes_291.txt input/cameras/four_cubes/four_cubes_291.txt 
./raytracer input/scenes/four_cubes/four_cubes_292.txt input/cameras/four_cubes/four_cubes_292.txt 
./raytracer input/scenes/four_cubes/four_cubes_293.txt input/cameras/four_cubes/four_cubes_293.txt 
./raytracer input/scenes/four_cubes/four_cubes_294.txt input/cameras/four_cubes/four_cubes_294.txt 
./raytracer input/scenes/four_cubes/four_cubes_295.txt input/cameras/four_cubes/four_cubes_295.txt 
./raytracer input/scenes/four_cubes/four_cubes_296.txt input/cameras/four_cubes/four_cubes_296.txt 
./raytracer input/scenes/four_cubes/four_cubes_297.txt input/cameras/four_cubes/four_cubes_297.txt 
./raytracer input/scenes/four_cubes/four_cubes_298.txt input/cameras/four_cubes/four_cubes_298.txt 
./raytracer input/scenes/four_cubes/four_cubes_299.txt input/cameras/four_cubes/four_cubes_299.txt 
./raytracer input/scenes/four_cubes/four_cubes_300.txt input/cameras/four_cubes/four_cubes_300.txt 
./raytracer input/scenes/four_cubes/four_cubes_301.txt input/cameras/four_cubes/four_cubes_301.txt 
./raytracer input/scenes/four_cubes/four_cubes_302.txt input/cameras/four_cubes/four_cubes_302.txt 
./raytracer input/scenes/four_cubes/four_cubes_303.txt input/cameras/four_cubes/four_cubes_303.txt 
./raytracer input/scenes/four_cubes/four_cubes_304.txt input/cameras/four_cubes/four_cubes_304.txt 
./raytracer input/scenes/four_cubes/four_cubes_305.txt input/cameras/four_cubes/four_cubes_305.txt 
./raytracer input/scenes/four_cubes/four_cubes_306.txt input/cameras/four_cubes/four_cubes_306.txt 
./raytracer input/scenes/four_cubes/four_cubes_307.txt input/cameras/four_cubes/four_cubes_307.txt 
./raytracer input/scenes/four_cubes/four_cubes_308.txt input/cameras/four_cubes/four_cubes_308.txt 
./raytracer input/scenes/four_cubes/four_cubes_309.txt input/cameras/four_cubes/four_cubes_309.txt 
./raytracer input/scenes/four_cubes/four_cubes_310.txt input/cameras/four_cubes/four_cubes_310.txt 
./raytracer input/scenes/four_cubes/four_cubes_311.txt input/cameras/four_cubes/four_cubes_311.txt 
./raytracer input/scenes/four_cubes/four_cubes_312.txt input/cameras/four_cubes/four_cubes_312.txt 
./raytracer input/scenes/four_cubes/four_cubes_313.txt input/cameras/four_cubes/four_cubes_313.txt 
./raytracer input/scenes/four_cubes/four_cubes_314.txt input/cameras/four_cubes/four_cubes_314.txt 
./raytracer input/scenes/four_cubes/four_cubes_315.txt input/cameras/four_cubes/four_cubes_315.txt 
./raytracer input/scenes/four_cubes/four_cubes_316.txt input/cameras/four_cubes/four_cubes_316.txt 
./raytracer input/scenes/four_cubes/four_cubes_317.txt input/cameras/four_cubes/four_cubes_317.txt 
./raytracer input/scenes/four_cubes/four_cubes_318.txt input/cameras/four_cubes/four_cubes_318.txt  
./raytracer input/scenes/four_cubes/four_cubes_319.txt input/cameras/four_cubes/four_cubes_319.txt 
./raytracer input/scenes/four_cubes/four_cubes_320.txt input/cameras/four_cubes/four_cubes_320.txt 
./raytracer input/scenes/four_cubes/four_cubes_321.txt input/cameras/four_cubes/four_cubes_321.txt 
./raytracer input/scenes/four_cubes/four_cubes_322.txt input/cameras/four_cubes/four_cubes_322.txt 
./raytracer input/scenes/four_cubes/four_cubes_323.txt input/cameras/four_cubes/four_cubes_323.txt 
./raytracer input/scenes/four_cubes/four_cubes_324.txt input/cameras/four_cubes/four_cubes_324.txt 
./raytracer input/scenes/four_cubes/four_cubes_325.txt input/cameras/four_cubes/four_cubes_325.txt 
./raytracer input/scenes/four_cubes/four_cubes_326.txt input/cameras/four_cubes/four_cubes_326.txt 
./raytracer input/scenes/four_cubes/four_cubes_327.txt input/cameras/four_cubes/four_cubes_327.txt 
./raytracer input/scenes/four_cubes/four_cubes_328.txt input/cameras/four_cubes/four_cubes_328.txt 
./raytracer input/scenes/four_cubes/four_cubes_329.txt input/cameras/four_cubes/four_cubes_329.txt 
./raytracer input/scenes/four_cubes/four_cubes_330.txt input/cameras/four_cubes/four_cubes_330.txt 
./raytracer input/scenes/four_cubes/four_cubes_331.txt input/cameras/four_cubes/four_cubes_331.txt 
./raytracer input/scenes/four_cubes/four_cubes_332.txt input/cameras/four_cubes/four_cubes_332.txt 
./raytracer input/scenes/four_cubes/four_cubes_333.txt input/cameras/four_cubes/four_cubes_333.txt 
./raytracer input/scenes/four_cubes/four_cubes_334.txt input/cameras/four_cubes/four_cubes_334.txt 
./raytracer input/scenes/four_cubes/four_cubes_335.txt input/cameras/four_cubes/four_cubes_335.txt 
./raytracer input/scenes/four_cubes/four_cubes_336.txt input/cameras/four_cubes/four_cubes_336.txt 
./raytracer input/scenes/four_cubes/four_cubes_337.txt input/cameras/four_cubes/four_cubes_337.txt 
./raytracer input/scenes/four_cubes/four_cubes_338.txt input/cameras/four_cubes/four_cubes_338.txt 
./raytracer input/scenes/four_cubes/four_cubes_339.txt input/cameras/four_cubes/four_cubes_339.txt 
./raytracer input/scenes/four_cubes/four_cubes_340.txt input/cameras/four_cubes/four_cubes_340.txt 
./raytracer input/scenes/four_cubes/four_cubes_341.txt input/cameras/four_cubes/four_cubes_341.txt 
./raytracer input/scenes/four_cubes/four_cubes_342.txt input/cameras/four_cubes/four_cubes_342.txt 
./raytracer input/scenes/four_cubes/four_cubes_343.txt input/cameras/four_cubes/four_cubes_343.txt 
./raytracer input/scenes/four_cubes/four_cubes_344.txt input/cameras/four_cubes/four_cubes_344.txt 
./raytracer input/scenes/four_cubes/four_cubes_345.txt input/cameras/four_cubes/four_cubes_345.txt 
./raytracer input/scenes/four_cubes/four_cubes_346.txt input/cameras/four_cubes/four_cubes_346.txt 
./raytracer input/scenes/four_cubes/four_cubes_347.txt input/cameras/four_cubes/four_cubes_347.txt 
./raytracer input/scenes/four_cubes/four_cubes_348.txt input/cameras/four_cubes/four_cubes_348.txt 
./raytracer input/scenes/four_cubes/four_cubes_349.txt input/cameras/four_cubes/four_cubes_349.txt 
./raytracer input/scenes/four_cubes/four_cubes_350.txt input/cameras/four_cubes/four_cubes_350.txt 
./raytracer input/scenes/four_cubes/four_cubes_351.txt input/cameras/four_cubes/four_cubes_351.txt 
./raytracer input/scenes/four_cubes/four_cubes_352.txt input/cameras/four_cubes/four_cubes_352.txt 
./raytracer input/scenes/four_cubes/four_cubes_353.txt input/cameras/four_cubes/four_cubes_353.txt 
./raytracer input/scenes/four_cubes/four_cubes_354.txt input/cameras/four_cubes/four_cubes_354.txt 
./raytracer input/scenes/four_cubes/four_cubes_355.txt input/cameras/four_cubes/four_cubes_355.txt 
./raytracer input/scenes/four_cubes/four_cubes_356.txt input/cameras/four_cubes/four_cubes_356.txt 
./raytracer input/scenes/four_cubes/four_cubes_357.txt input/cameras/four_cubes/four_cubes_357.txt 
./raytracer input/scenes/four_cubes/four_cubes_358.txt input/cameras/four_cubes/four_cubes_358.txt 
./raytracer input/scenes/four_cubes/four_cubes_359.txt input/cameras/four_cubes/four_cubes_359.txt 
./raytracer input/scenes/four_cubes/four_cubes_360.txt input/cameras/four_cubes/four_cubes_360.txt 