./raytracer input/scenes/four_cubes/four_cubes_000.txt input/cameras/four_cubes/four_cubes_000.txt 
./raytracer input/scenes/four_cubes/four_cubes_001.txt input/cameras/four_cubes/four_cubes_001.txt 
./raytracer input/scenes/four_cubes/four_cubes_002.txt input/cameras/four_cubes/four_cubes_002.txt 
./raytracer input/scenes/four_cubes/four_cubes_003.txt input/cameras/four_cubes/four_cubes_003.txt 
./raytracer input/scenes/four_cubes/four_cubes_004.txt input/cameras/four_cubes/four_cubes_004.txt 
./raytracer input/scenes/four_cubes/four_cubes_005.txt input/cameras/four_cubes/four_cubes_005.txt 
./raytracer input/scenes/four_cubes/four_cubes_006.txt input/cameras/four_cubes/four_cubes_006.txt 
./raytracer input/scenes/four_cubes/four_cubes_007.txt input/cameras/four_cubes/four_cubes_007.txt 
./raytracer input/scenes/four_cubes/four_cubes_008.txt input/cameras/four_cubes/four_cubes_008.txt 
./raytracer input/scenes/four_cubes/four_cubes_009.txt input/cameras/four_cubes/four_cubes_009.txt 
./raytracer input/scenes/four_cubes/four_cubes_010.txt input/cameras/four_cubes/four_cubes_010.txt 
./raytracer input/scenes/four_cubes/four_cubes_011.txt input/cameras/four_cubes/four_cubes_011.txt 
./raytracer input/scenes/four_cubes/four_cubes_012.txt input/cameras/four_cubes/four_cubes_012.txt 
./raytracer input/scenes/four_cubes/four_cubes_013.txt input/cameras/four_cubes/four_cubes_013.txt 
./raytracer input/scenes/four_cubes/four_cubes_014.txt input/cameras/four_cubes/four_cubes_014.txt 
./raytracer input/scenes/four_cubes/four_cubes_015.txt input/cameras/four_cubes/four_cubes_015.txt 
./raytracer input/scenes/four_cubes/four_cubes_016.txt input/cameras/four_cubes/four_cubes_016.txt 
./raytracer input/scenes/four_cubes/four_cubes_017.txt input/cameras/four_cubes/four_cubes_017.txt 
./raytracer input/scenes/four_cubes/four_cubes_018.txt input/cameras/four_cubes/four_cubes_018.txt  
./raytracer input/scenes/four_cubes/four_cubes_019.txt input/cameras/four_cubes/four_cubes_019.txt 
./raytracer input/scenes/four_cubes/four_cubes_020.txt input/cameras/four_cubes/four_cubes_020.txt 
./raytracer input/scenes/four_cubes/four_cubes_021.txt input/cameras/four_cubes/four_cubes_021.txt 
./raytracer input/scenes/four_cubes/four_cubes_022.txt input/cameras/four_cubes/four_cubes_022.txt 
./raytracer input/scenes/four_cubes/four_cubes_023.txt input/cameras/four_cubes/four_cubes_023.txt 
./raytracer input/scenes/four_cubes/four_cubes_024.txt input/cameras/four_cubes/four_cubes_024.txt 
./raytracer input/scenes/four_cubes/four_cubes_025.txt input/cameras/four_cubes/four_cubes_025.txt 
./raytracer input/scenes/four_cubes/four_cubes_026.txt input/cameras/four_cubes/four_cubes_026.txt 
./raytracer input/scenes/four_cubes/four_cubes_027.txt input/cameras/four_cubes/four_cubes_027.txt 
./raytracer input/scenes/four_cubes/four_cubes_028.txt input/cameras/four_cubes/four_cubes_028.txt 
./raytracer input/scenes/four_cubes/four_cubes_029.txt input/cameras/four_cubes/four_cubes_029.txt 
./raytracer input/scenes/four_cubes/four_cubes_030.txt input/cameras/four_cubes/four_cubes_030.txt 
./raytracer input/scenes/four_cubes/four_cubes_031.txt input/cameras/four_cubes/four_cubes_031.txt 
./raytracer input/scenes/four_cubes/four_cubes_032.txt input/cameras/four_cubes/four_cubes_032.txt 
./raytracer input/scenes/four_cubes/four_cubes_033.txt input/cameras/four_cubes/four_cubes_033.txt 
./raytracer input/scenes/four_cubes/four_cubes_034.txt input/cameras/four_cubes/four_cubes_034.txt 
./raytracer input/scenes/four_cubes/four_cubes_035.txt input/cameras/four_cubes/four_cubes_035.txt 
./raytracer input/scenes/four_cubes/four_cubes_036.txt input/cameras/four_cubes/four_cubes_036.txt 
./raytracer input/scenes/four_cubes/four_cubes_037.txt input/cameras/four_cubes/four_cubes_037.txt 
./raytracer input/scenes/four_cubes/four_cubes_038.txt input/cameras/four_cubes/four_cubes_038.txt 
./raytracer input/scenes/four_cubes/four_cubes_039.txt input/cameras/four_cubes/four_cubes_039.txt 
./raytracer input/scenes/four_cubes/four_cubes_040.txt input/cameras/four_cubes/four_cubes_040.txt 
./raytracer input/scenes/four_cubes/four_cubes_041.txt input/cameras/four_cubes/four_cubes_041.txt 
./raytracer input/scenes/four_cubes/four_cubes_042.txt input/cameras/four_cubes/four_cubes_042.txt 
./raytracer input/scenes/four_cubes/four_cubes_043.txt input/cameras/four_cubes/four_cubes_043.txt 
./raytracer input/scenes/four_cubes/four_cubes_044.txt input/cameras/four_cubes/four_cubes_044.txt 
./raytracer input/scenes/four_cubes/four_cubes_045.txt input/cameras/four_cubes/four_cubes_045.txt 
./raytracer input/scenes/four_cubes/four_cubes_046.txt input/cameras/four_cubes/four_cubes_046.txt 
./raytracer input/scenes/four_cubes/four_cubes_047.txt input/cameras/four_cubes/four_cubes_047.txt 
./raytracer input/scenes/four_cubes/four_cubes_048.txt input/cameras/four_cubes/four_cubes_048.txt 
./raytracer input/scenes/four_cubes/four_cubes_049.txt input/cameras/four_cubes/four_cubes_049.txt 
./raytracer input/scenes/four_cubes/four_cubes_050.txt input/cameras/four_cubes/four_cubes_050.txt 
./raytracer input/scenes/four_cubes/four_cubes_051.txt input/cameras/four_cubes/four_cubes_051.txt 
./raytracer input/scenes/four_cubes/four_cubes_052.txt input/cameras/four_cubes/four_cubes_052.txt 
./raytracer input/scenes/four_cubes/four_cubes_053.txt input/cameras/four_cubes/four_cubes_053.txt 
./raytracer input/scenes/four_cubes/four_cubes_054.txt input/cameras/four_cubes/four_cubes_054.txt 
./raytracer input/scenes/four_cubes/four_cubes_055.txt input/cameras/four_cubes/four_cubes_055.txt 
./raytracer input/scenes/four_cubes/four_cubes_056.txt input/cameras/four_cubes/four_cubes_056.txt 
./raytracer input/scenes/four_cubes/four_cubes_057.txt input/cameras/four_cubes/four_cubes_057.txt 
./raytracer input/scenes/four_cubes/four_cubes_058.txt input/cameras/four_cubes/four_cubes_058.txt 
./raytracer input/scenes/four_cubes/four_cubes_059.txt input/cameras/four_cubes/four_cubes_059.txt 
./raytracer input/scenes/four_cubes/four_cubes_060.txt input/cameras/four_cubes/four_cubes_060.txt 
./raytracer input/scenes/four_cubes/four_cubes_061.txt input/cameras/four_cubes/four_cubes_061.txt 
./raytracer input/scenes/four_cubes/four_cubes_062.txt input/cameras/four_cubes/four_cubes_062.txt 
./raytracer input/scenes/four_cubes/four_cubes_063.txt input/cameras/four_cubes/four_cubes_063.txt 
./raytracer input/scenes/four_cubes/four_cubes_064.txt input/cameras/four_cubes/four_cubes_064.txt 
./raytracer input/scenes/four_cubes/four_cubes_065.txt input/cameras/four_cubes/four_cubes_065.txt 
./raytracer input/scenes/four_cubes/four_cubes_066.txt input/cameras/four_cubes/four_cubes_066.txt 
./raytracer input/scenes/four_cubes/four_cubes_067.txt input/cameras/four_cubes/four_cubes_067.txt 
./raytracer input/scenes/four_cubes/four_cubes_068.txt input/cameras/four_cubes/four_cubes_068.txt 
./raytracer input/scenes/four_cubes/four_cubes_069.txt input/cameras/four_cubes/four_cubes_069.txt 
./raytracer input/scenes/four_cubes/four_cubes_070.txt input/cameras/four_cubes/four_cubes_070.txt 
./raytracer input/scenes/four_cubes/four_cubes_071.txt input/cameras/four_cubes/four_cubes_071.txt 
./raytracer input/scenes/four_cubes/four_cubes_072.txt input/cameras/four_cubes/four_cubes_072.txt 
./raytracer input/scenes/four_cubes/four_cubes_073.txt input/cameras/four_cubes/four_cubes_073.txt 
./raytracer input/scenes/four_cubes/four_cubes_074.txt input/cameras/four_cubes/four_cubes_074.txt 
./raytracer input/scenes/four_cubes/four_cubes_075.txt input/cameras/four_cubes/four_cubes_075.txt 
./raytracer input/scenes/four_cubes/four_cubes_076.txt input/cameras/four_cubes/four_cubes_076.txt 
./raytracer input/scenes/four_cubes/four_cubes_077.txt input/cameras/four_cubes/four_cubes_077.txt 
./raytracer input/scenes/four_cubes/four_cubes_078.txt input/cameras/four_cubes/four_cubes_078.txt 
./raytracer input/scenes/four_cubes/four_cubes_079.txt input/cameras/four_cubes/four_cubes_079.txt 
./raytracer input/scenes/four_cubes/four_cubes_080.txt input/cameras/four_cubes/four_cubes_080.txt 
./raytracer input/scenes/four_cubes/four_cubes_081.txt input/cameras/four_cubes/four_cubes_081.txt 
./raytracer input/scenes/four_cubes/four_cubes_082.txt input/cameras/four_cubes/four_cubes_082.txt 
./raytracer input/scenes/four_cubes/four_cubes_083.txt input/cameras/four_cubes/four_cubes_083.txt 
./raytracer input/scenes/four_cubes/four_cubes_084.txt input/cameras/four_cubes/four_cubes_084.txt 
./raytracer input/scenes/four_cubes/four_cubes_085.txt input/cameras/four_cubes/four_cubes_085.txt 
./raytracer input/scenes/four_cubes/four_cubes_086.txt input/cameras/four_cubes/four_cubes_086.txt 
./raytracer input/scenes/four_cubes/four_cubes_087.txt input/cameras/four_cubes/four_cubes_087.txt 
./raytracer input/scenes/four_cubes/four_cubes_088.txt input/cameras/four_cubes/four_cubes_088.txt 
./raytracer input/scenes/four_cubes/four_cubes_089.txt input/cameras/four_cubes/four_cubes_089.txt 
./raytracer input/scenes/four_cubes/four_cubes_090.txt input/cameras/four_cubes/four_cubes_090.txt 